Ot_Shop/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'




urlpatterns=[
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    
    
]

Ot_Shop/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name ='App_Order'

urlpatterns = [

    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/',views.remove_from_cart, name="remove"),
    path('cart/',views.cart_view, name="cart"),
    path('increase/<pk>',views.increase_cart, name="increase"),
    path('decrease/<pk>',views.decrease_cart, name="decrease"),

    

]

Ot_Shop/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns=[
    path('',views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    
    
    
]

Ot_Shop/First_App/urls.py
from django.urls import path
from First_App import views

app_name = 'First_App'

urlpatterns=[
    
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
       
    
]

Ot_Shop/Ot_Shop/urls.py
from django.contrib import admin
from django.urls import path, include

#To Show media MEDIA_Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment',include('App_Payment.urls')),
    path('',include('First_App.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ot_Shop/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
   
    
    
    <title>{% block title_block %} LPFASHION {% endblock %}</title>





    <style>
        .card{
            height: 350px;
        }

        .card-product:after{
            content: "";
            display: table;
            clear: both;
            visibility: hidden;

        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;
        }

        .card-product .price-old{
            color: #999;
        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

        .card-product .img-wrap img{
            min-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap{
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .title{
            margin-top: 0px;
        }

    </style>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/emailjs-com@2/dist/email.min.js"></script>
<script type="text/javascript">
(function() {
emailjs.init("user_JegwN2JYR03exvXsYURDN");
})();
</script>


</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}

                    <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                {% endfor %}
            {% endif %}
            

        </div>
        {% block body_block %} {% endblock %}

    </div>
    
    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Ot_Shop/templates/footer.html
{% load cart_tag %}

<footer class="" style="background-color: #092E5A; padding-top: 10px; padding-bottom: 10px; margin-top: 250px;">
    <div class="container">
      
        
      <div class="row">
        <div class="col-6">
          <div style="margin-left: 200px;">
                <p style=" color: white; font-size: 18px;">You can find us!</p>
                <a href=""><i class="fab fa-facebook mr-3" style="font-size: 18px; color: aliceblue;"></i></a> 
                <a href=""><i class="fab fa-twitter mr-3"style="font-size: 18px; color: aliceblue;"></i></a>
                <a href=""><i class="fab fa-instagram mr-3"style="font-size: 18px; color: aliceblue;"></i></a>
           
               <a href=""><i class="fab fa-linkedin mr-3"style="font-size: 18px; color: aliceblue;"></i></a>
              </div>
        </div>
        <div class="col-6">
          <div style="margin-left: 150px;">
          <i class="fas fa-search-location" style="font-size: 18px; color: aliceblue;"></i> <span style="font-size: 18px; color: aliceblue; margin-left: 5px;">Mojumdari,Sylhet</span>
          <br>
          <i class="fas fa-phone"style="font-size: 18px; color: aliceblue;"></i><span style="font-size: 18px; color: aliceblue; margin-left: 5px;">(+880)1733933859</span>
          <br>
          <i class="fas fa-envelope"style="font-size: 18px; color: aliceblue;"></i><span style="font-size: 18px; color: aliceblue; margin-left: 5px;">abutalhapappu@gmail.com</span>
        </div>
        </div>
      </div>


    </div>

  </footer>
  <div class="bg-success py-2">
    <span style="margin-left: 700px;">&copy; 2021 LPFASHION</span>
        
  </div>  

Ot_Shop/templates/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
   
    
    
    <title>{% block title_block %} LPFASHION {% endblock %}</title>





    <style>
        .card{
            height: 350px;
        }

        .card-product:after{
            content: "";
            display: table;
            clear: both;
            visibility: hidden;

        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;
        }

        .card-product .price-old{
            color: #999;
        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

        .card-product .img-wrap img{
            min-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap{
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .title{
            margin-top: 0px;
        }

    </style>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/emailjs-com@2/dist/email.min.js"></script>
<script type="text/javascript">
(function() {
emailjs.init("user_JegwN2JYR03exvXsYURDN");
})();
</script>


</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}

                    <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                {% endfor %}
            {% endif %}
            

        </div>
        {% block body_block %} {% endblock %}

    </div>
    
    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Ot_Shop/templates/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg" style="background-color: #092E5A;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}" style="color: #C50909; font-weight: bold;"><h2>LPFASHION</h2></a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                
                <a href="{% url 'First_App:about' %}" class="nav-link" ><li class="nav-item mr-2 text-light">About</li></a>
                <a href="{% url 'First_App:contact' %}" class="nav-link" ><li class="nav-item mr-2 text-light">Contact</li></a>
            
            {% if request.user.is_authenticated %}
               <a href="{% url 'App_Order:cart' %}" class="nav-link"> 
                   <li class="nav-item">
                        <i class="fa fa-shopping-cart text-light"></i> Cart

                        <span class="badge badge-light">{{ request.user | cart_total }}</span>

                    </li>
                </a>
                
                <li class="nav-item dropdown">

                    <a href="" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >

                        <i class="fas fa-user-tie text-light"></i>
                            {{ request.user.profile.username }}

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a href="{% url 'App_Login:profile' %}" class="dropdown-item">Profile</a>
                        
                        <div class="dropdown-driver"></div>
                        <a href="{% url 'App_Login:logout' %}" class="dropdown-item">Logout</a>

                    </div>

                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'App_Login:login' %}" class="btn text-light nav-link">Login</a>

                </li>
                {% endif %}
            </ul>
        </div>


    </div>

</nav>  