Ot_Shop/App_Payment/urls.py
from django.contrib.staticfiles.urls import urlpatterns
from django.urls import path
from App_Payment import views

app_name = "App_Payment"

urlpatterns=[

    path('checkout/',views.checkout, name="checkout"),
    path('payment/',views.payment, name="payment"),
]

Ot_Shop/Ot_Shop/urls.py
from django.contrib import admin
from django.urls import path, include

#To Show media MEDIA_Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment',include('App_Payment.urls')),
    path('',include('First_App.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ot_Shop/App_Payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=264, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f'{self.user.profile.username} billing address'

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self,field_name)
            if value is None or value=='':
                return False
        return True

    class meta:
        verbose_name_plural ="Billing Addresses"

Ot_Shop/App_Payment/forms.py
from django import forms
from App_Payment.models import BillingAddress

class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address','zipcode','city','country']

Ot_Shop/App_Payment/views.py
from django.shortcuts import render, HttpResponseRedirect,redirect
from django.contrib import messages


#models and forms
from App_Order.models import Order
from App_Payment.forms import BillingAddress
from App_Payment.forms import BillingForm

from django.contrib.auth.decorators import login_required

#For Paymennt





# Create your views here.

@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]

    form = BillingForm(instance=saved_address)
    if request.method =="POST":
        form = BillingForm(request.POST, instance=saved_address)
        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request, f"Shipping Address Saved!")
    
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    print(order_qs)
    order_items = order_qs[0].orderitems.all()
    print(order_items)
    order_total = order_qs[0].get_totals()

    return render(request, 'App_Payment/checkout.html', context={"form":form,"order_items":order_items,"order_total":order_total, "saved_address":saved_address})



@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    if not saved_address[0].is_fully_filled():
        messages.info(request, f"Please Complete Shipping Address")
        return redirect("App_Payment:checkout")

    if not request.user.profile.is_fully_filled():
        messages.info(request, f"Please Complete Profile Details")
        return redirect("App_Login:profile")
    
    return render(request,"App_Payment/payment.html", context={})

Ot_Shop/templates/App_Payment/checkout.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address > <span class="text-muted">Checkout</span>

    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height: auto;">
                <div class="card-body">
                    <form method="POST">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary float-right">Save Address</button>

                    </form>
                </div>

            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="height: auto;">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for order_item in order_items %}
                        <li class="list-group-item">
                            {{order_item.item.name}} X {{ order_item.quantity }}
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="card-footer">
                    <span class="float-left"><b>Order Total</b></span>
                    <span class="float-right"><b>&#2547; {{ order_total|floatformat:2 }}</b></span>
                </div>        

            </div>
            <br>
            <br>
            {% if saved_address.is_fully_filled %}
                <a href="{% url 'App_Payment:payment' %}" class="btn btn-warning btn-lg">Make Payment</a>
            {% else %}
            <div class="alert alert-info">
                <p>Please fill up all the information to make the payment.</p>

            </div>

            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

Ot_Shop/templates/App_Payment/payment.html
{% extends 'index.html' %}
{% block body_block %}


<div class="row">
    <div class="col-6">
        <b>Bkash</b><img src="/media/b.svg" alt="" style="width: 50px;"><b>: 01733378378</b>
        <br>
        <br>
        <b>Nagad</b><img src="/media/n.svg" alt="" style="width: 50px;"><b>: 01733378378</b>
        <br>
        <br>
        <b>Rocket</b><img src="/media/r.png" alt="" style="width: 40px;"><b>: 01733378378</b>
       

    </div>
    <div class="col-6">
        <h3 style="color: #EC7063; font-weight: bold;">Give the transaction id !</h3>
        <p>Give the more information!</p>

        <form action="javascript:sendmail()" method="post">
            
                <div class="form-group form-inline">
                    <input required style="width: 437px;"  type="text" class="form-control" name="fname" id="fname" placeholder="Product Name">
                </div>

                <div class="form-group form-inline">
                    <input required type="text" class="form-control" id="pid" placeholder="Product Code">
                    <input required type="text" class="form-control ml-2" id="bkash" placeholder="Bkash Number">
                </div>
                <div class="form-group">
                    
                    <textarea style="width: 82%;" class="form-control" rows="2" id="tid" placeholder="Transaction Id"></textarea>
                  </div>
            
            <button type="submit" class="btn btn-md text-light" style="background-color: #EC7063; margin-bottom: 0px;">Submit</button>
          </form>

    </div>
</div>



<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> -->
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
<script src="https://smtpjs.com/v3/smtp.js"></script>
 
<script>  

     function sendmail(){
    
			var name = $('#fname').val();
           
			var pid = $('#pid').val();
            var bkash = $('#bkash').val();
            var tid = $('#tid').val();

			// var body = $('#body').val();

			var Body='Product Name: '+name+' <br>PID: '+pid+'<br>Bkash Number: '+bkash+'<br>Trasaction Id: '+tid;
			//console.log(name, phone, email, message);

			Email.send({
        SecureToken:"fbf31702-bb7f-4a4e-9c1c-4ccf17ee777f",
				To: 'abulkashemlukman@gmail.com',
				From: "abulkashemlukman@gmail.com",
				Subject: "New message on contact from "+name,
				Body: Body
			}).then(
				message =>{
					//console.log (message);
					if(message=='OK'){
					alert('Your mail has been send. Thank you for connecting.');
					}
					else{
						console.error (message);
						alert('There is error at sending message. ')
						
					}

				}
			);



		}


    </script>

    
{% endblock %}